
# this is used to take a full state name and provide the abbreviated 2 character state code required for the plotly heatmap
st_abr_dic = {'alaska': 'AK', 
              'alabama': 'AL', 
              'arkansas': 'AR', 
              'arizona': 'AZ', 
              'california': 'CA', 
              'colorado': 'CO', 
              'connecticut': 'CT', 
              'delaware': 'DE', 
              'florida': 'FL', 
              'georgia': 'GA', 
              'hawaii': 'HI', 
              'iowa': 'IA', 
              'idaho': 'ID', 
              'illinois': 'IL', 
              'indiana': 'IN', 
              'kansas': 'KS', 
              'kentucky': 'KY', 
              'louisiana': 'LA', 
              'massachusetts': 'MA', 
              'maryland': 'MD', 
              'maine': 'ME', 
              'michigan': 'MI', 
              'minnesota': 'MN', 
              'missouri': 'MO', 
              'mississippi': 'MS', 
              'montana': 'MT', 
              'north carolina': 'NC', 
              'north dakota': 'ND', 
              'nebraska': 'NE', 
              'new hampshire': 'NH', 
              'new jersey': 'NJ', 
              'new mexico': 'NM', 
              'nevada': 'NV', 
              'new york': 'NY', 
              'ohio': 'OH', 
              'oklahoma': 'OK', 
              'oregon': 'OR', 
              'pennsylvania': 'PA', 
              'rhode island': 'RI', 
              'south carolina': 'SC', 
              'south dakota': 'SD', 
              'tennessee': 'TN', 
              'texas': 'TX', 
              'utah': 'UT', 
              'virginia': 'VA', 
              'vermont': 'VT', 
              'washington': 'WA', 
              'wisconsin': 'WI', 
              'west virginia': 'WV', 
              'wyoming': 'WY', 
              'district of columbia': 'DC'
              }
